name: chromoformer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pandas=1.3.0
  - scikit-learn=0.24.2
  - numpy=1.21.0
  - tqdm=4.61.2
  - snakemake=6.5.3
  - sambamba=0.6.8
  - bedtools=2.23.0